import type { ElementType } from "react";
import {
  AlertTriangle,
  Briefcase,
  CheckCircle2,
  CircleSlash,
  ClipboardList,
  FileCheck2,
  FilePlus2,
  FileX2,
  MessageCircle,
  Pencil,
  RotateCcw,
  Send,
  Settings,
  ShieldCheck,
  Stethoscope,
  Trash2,
  Undo2,
  UserCheck,
  UserCog,
  UserPlus,
  UserX,
  Users,
  Workflow,
  XCircle,
} from "lucide-react";
import type { ActivityIcon } from "@/lib/activity/catalog";

/** Ícone lógico do catálogo de atividades → lucide. Neutro: usado no servidor e no cliente. */
export const ACTIVITY_ICONS: Record<ActivityIcon, ElementType> = {
  created: FilePlus2,
  edit: Pencil,
  stage: Workflow,
  done: CheckCircle2,
  exam: Stethoscope,
  "form-sent": Send,
  form: ClipboardList,
  whatsapp: MessageCircle,
  "doc-ok": FileCheck2,
  "doc-bad": FileX2,
  undo: Undo2,
  send: Send,
  approve: CheckCircle2,
  reject: XCircle,
  return: RotateCcw,
  cancel: CircleSlash,
  reopen: RotateCcw,
  job: Briefcase,
  position: Briefcase,
  candidate: Users,
  "user-plus": UserPlus,
  user: UserCog,
  shield: ShieldCheck,
  "user-off": UserX,
  "user-on": UserCheck,
  trash: Trash2,
  settings: Settings,
  alert: AlertTriangle,
};
